# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 661)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setWhatsThis("")
        self.tabWidget_2.setAccessibleName("")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(20, 10, 851, 81))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.source_btn = QtWidgets.QPushButton(self.frame_4)
        self.source_btn.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.source_btn.setProperty("id", 10001)
        self.source_btn.setObjectName("source_btn")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_5.setObjectName("label_5")
        self.source_dir = QtWidgets.QLineEdit(self.frame_4)
        self.source_dir.setGeometry(QtCore.QRect(80, 10, 600, 20))
        self.source_dir.setObjectName("source_dir")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(20, 100, 851, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.pushButton_5.setProperty("id", 10002)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_6.setObjectName("label_6")
        self.template_dir = QtWidgets.QLineEdit(self.frame_5)
        self.template_dir.setGeometry(QtCore.QRect(170, 10, 600, 20))
        self.template_dir.setObjectName("template_dir")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 300, 101, 16))
        self.label_7.setObjectName("label_7")
        self.web_name = QtWidgets.QLineEdit(self.tab)
        self.web_name.setGeometry(QtCore.QRect(120, 300, 211, 20))
        self.web_name.setObjectName("web_name")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(20, 190, 851, 81))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.pushButton_6.setProperty("id", 10003)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_8.setObjectName("label_8")
        self.static_dir = QtWidgets.QLineEdit(self.frame_6)
        self.static_dir.setGeometry(QtCore.QRect(90, 10, 600, 20))
        self.static_dir.setObjectName("static_dir")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 350, 91, 23))
        self.pushButton.setProperty("id", 10004)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 350, 91, 21))
        self.pushButton_2.setProperty("id", 10005)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 350, 91, 21))
        self.pushButton_3.setProperty("id", 10006)
        self.pushButton_3.setObjectName("pushButton_3")
        self.action_log = QtWidgets.QTextBrowser(self.tab)
        self.action_log.setEnabled(True)
        self.action_log.setGeometry(QtCore.QRect(350, 280, 531, 101))
        self.action_log.setObjectName("action_log")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(-10, 260, 901, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(880, -10, 16, 401))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(0, 380, 888, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(0, 180, 888, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 888, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 19))
        self.menubar.setObjectName("menubar")
        self.menu1 = QtWidgets.QMenu(self.menubar)
        self.menu1.setObjectName("menu1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu1.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.source_btn.clicked.connect(MainWindow.select_dir)
        self.pushButton_5.clicked.connect(MainWindow.select_dir)
        self.pushButton_6.clicked.connect(MainWindow.select_dir)
        self.pushButton.clicked.connect(MainWindow.select_dir)
        self.pushButton_2.clicked.connect(MainWindow.select_dir)
        self.pushButton_3.clicked.connect(MainWindow.select_dir)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.source_btn.setText(_translate("MainWindow", "选择文件夹"))
        self.label_5.setText(_translate("MainWindow", "源文件路径:"))
        self.pushButton_5.setText(_translate("MainWindow", "选择文件夹"))
        self.label_6.setText(_translate("MainWindow", "template中存放网页的路径:"))
        self.label_7.setText(_translate("MainWindow", "网页文件夹命名:"))
        self.pushButton_6.setText(_translate("MainWindow", "选择文件夹"))
        self.label_8.setText(_translate("MainWindow", "static路径:"))
        self.pushButton.setText(_translate("MainWindow", "我已确认:执行"))
        self.pushButton_2.setText(_translate("MainWindow", "存储操作"))
        self.pushButton_3.setText(_translate("MainWindow", "读取操作"))
        self.action_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "网页模板导入"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menu1.setTitle(_translate("MainWindow", "1"))

