# Generated by Django 2.0 on 2018-12-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('isdir', models.BooleanField(default=True)),
                ('tags', models.CharField(default='', max_length=500)),
                ('abs_path', models.CharField(max_length=500)),
                ('rel_path', models.CharField(max_length=300)),
                ('type', models.IntegerField()),
                ('c_id', models.IntegerField(default=0)),
                ('parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Mryang_Tdb.Dir')),
            ],
            options={
                'db_table': 'Mryang_App_dir',
            },
        ),
        migrations.CreateModel(
            name='GalleryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('intro', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('thum', models.CharField(default='', max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('param1', models.CharField(default='', max_length=500)),
                ('param2', models.CharField(default='', max_length=500)),
                ('folder_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dir', to='Mryang_Tdb.Dir')),
            ],
            options={
                'db_table': 'Mryang_App_galleryinfo',
            },
        ),
    ]
