# Generated by Django 2.2 on 2019-04-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_Tdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryinfo',
            name='folder_key',
        ),
        migrations.DeleteModel(
            name='Dir',
        ),
        migrations.DeleteModel(
            name='GalleryInfo',
        ),
    ]
