# Generated by Django 2.2 on 2019-09-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('isdir', models.BooleanField(default=True)),
                ('tags', models.CharField(default='', max_length=500)),
                ('abs_path', models.CharField(max_length=500)),
                ('rel_path', models.CharField(max_length=300)),
                ('type', models.IntegerField()),
                ('c_id', models.IntegerField(default=0)),
                ('parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Mryang_App.Dir')),
            ],
        ),
        migrations.CreateModel(
            name='MPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0, verbose_name='文件夹的类型(1.src,2.desc)')),
                ('level', models.IntegerField(default=0, verbose_name='放置优先级,数字越大优先级越高')),
                ('drive_memory_mb', models.IntegerField(default=8192, verbose_name='磁盘剩余空间小于此数值时,不选择此路径')),
                ('param1', models.CharField(default='', max_length=500)),
                ('param2', models.CharField(default='', max_length=500)),
                ('dir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mryang_App.Dir')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_abs_path', models.CharField(max_length=500)),
                ('src_md5', models.CharField(default='', max_length=50)),
                ('desc_name', models.CharField(max_length=100)),
                ('ext', models.CharField(default='', max_length=20)),
                ('src_size', models.IntegerField(default=0)),
                ('mid_size', models.IntegerField(default=0)),
                ('src_width', models.IntegerField(default=0)),
                ('src_height', models.IntegerField(default=0)),
                ('mid_width', models.IntegerField(default=0)),
                ('mid_height', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=-1)),
                ('is_gif', models.BooleanField(default=False)),
                ('desc_mpath', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='min_mpath', to='Mryang_App.MPath')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('regist_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_path', models.FileField(null=True, upload_to='video/')),
                ('album_path', models.FileField(null=True, upload_to='album/')),
                ('upload_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mryang_App.User')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('intro', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('param1', models.CharField(default='', max_length=500)),
                ('param2', models.CharField(default='', max_length=500)),
                ('thum_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='Mryang_App.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abs_path', models.CharField(default='', max_length=500)),
                ('desc_path', models.CharField(default='', max_length=500)),
                ('m3u8_path', models.CharField(default='', max_length=500)),
                ('nginx_path', models.CharField(default='', max_length=500)),
                ('md5', models.CharField(default='', max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('file_name', models.CharField(default='', max_length=100)),
                ('codec_type', models.CharField(default='', max_length=20)),
                ('codec_long_name', models.CharField(default='', max_length=200)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('r_frame_rate', models.IntegerField(default=0)),
                ('avg_frame_rate', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=-1)),
                ('param1', models.CharField(default='', max_length=500)),
                ('param2', models.CharField(default='', max_length=500)),
                ('folder_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_dir', to='Mryang_App.Dir')),
            ],
        ),
    ]
