# Generated by Django 2.0 on 2018-12-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('intro', models.CharField(default='', max_length=500)),
                ('duration', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('source_size', models.IntegerField(default=0)),
                ('fps', models.IntegerField(default=0)),
                ('param1', models.CharField(default='', max_length=500)),
                ('param2', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='dir',
            name='abs_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dir',
            name='rel_path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dir',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryinfo',
            name='param1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryinfo',
            name='param2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='folder_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_dir', to='Mryang_App.Dir'),
        ),
    ]
