# Generated by Django 2.2 on 2019-09-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='desc_mpath',
        ),
        migrations.AddField(
            model_name='photo',
            name='desc_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='desc_dir', to='Mryang_App.Dir'),
        ),
        migrations.AddField(
            model_name='photo',
            name='src_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='src_dir', to='Mryang_App.Dir'),
        ),
    ]
