# Generated by Django 2.2 on 2019-06-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(default='', max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UpLoadDir',
        ),
        migrations.AddField(
            model_name='galleryinfo',
            name='abs_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='galleryinfo',
            name='desc_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='galleryinfo',
            name='desc_real_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='picinfo',
            name='gallery_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='Mryang_App.GalleryInfo'),
        ),
    ]
