# Generated by Django 2.2 on 2019-04-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0002_auto_20181226_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('abs_path', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('md5', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('file_name', models.CharField(default='', max_length=100)),
                ('codec_type', models.CharField(default='', max_length=20)),
                ('codec_long_name', models.CharField(default='', max_length=200)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('r_frame_rate', models.IntegerField(default=0)),
                ('avg_frame_rate', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=-1)),
                ('param1', models.CharField(default='', max_length=500)),
                ('param2', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MediaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('intro', models.CharField(default='', max_length=500)),
                ('duration', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('source_size', models.IntegerField(default=0)),
                ('fps', models.IntegerField(default=0)),
                ('param1', models.CharField(default='', max_length=500)),
                ('param2', models.CharField(default='', max_length=500)),
                ('folder_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_dir', to='Mryang_App.Dir')),
            ],
        ),
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
