# Generated by Django 2.2 on 2019-09-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0002_auto_20190918_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='desc_dir',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='src_dir',
        ),
        migrations.AddField(
            model_name='photo',
            name='desc_mpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='min_mpath', to='Mryang_App.MPath'),
        ),
        migrations.AddField(
            model_name='photo',
            name='src_mpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='src_mpath', to='Mryang_App.MPath'),
        ),
    ]
