# Generated by Django 2.2 on 2019-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0002_auto_20190625_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='picinfo',
            name='is_gif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picinfo',
            name='state',
            field=models.IntegerField(default=-1),
        ),
    ]
