# Generated by Django 2.2 on 2019-09-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0003_auto_20190918_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='desc_name',
            new_name='desc_dir',
        ),
    ]
