# Generated by Django 2.2 on 2019-06-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0003_auto_20190627_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picinfo',
            old_name='res',
            new_name='src_name',
        ),
    ]
