# Generated by Django 2.2 on 2019-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0004_auto_20190627_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='picinfo',
            name='ext',
            field=models.CharField(default='', max_length=20),
        ),
    ]
