# Generated by Django 2.2 on 2019-09-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0004_auto_20190918_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='desc_dir',
            new_name='desc_rela_path',
        ),
    ]
