# Generated by Django 2.2 on 2019-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0005_picinfo_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='picinfo',
            name='abs_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
