# Generated by Django 2.2 on 2019-09-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0005_auto_20190918_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_wall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_wall', to='Mryang_App.PhotoWall'),
        ),
    ]
