# Generated by Django 2.2 on 2019-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0006_picinfo_abs_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picinfo',
            name='src_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
