# Generated by Django 2.2 on 2019-07-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0007_auto_20190703_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picinfo',
            old_name='name',
            new_name='desc_name',
        ),
        migrations.RenameField(
            model_name='picinfo',
            old_name='abs_path',
            new_name='src_abs_path',
        ),
        migrations.RemoveField(
            model_name='picinfo',
            name='src_name',
        ),
        migrations.AddField(
            model_name='picinfo',
            name='m_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picinfo',
            name='m_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picinfo',
            name='m_width',
            field=models.IntegerField(default=0),
        ),
    ]
