# Generated by Django 2.2 on 2019-09-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0007_photowall_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ctime',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='photo',
            name='mtime',
            field=models.IntegerField(default=-1),
        ),
    ]
