# Generated by Django 2.2 on 2019-09-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0008_auto_20190928_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='src_crc32',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='src_abs_path',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
