# Generated by Django 2.2 on 2019-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0010_media_desc_mpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpath',
            name='path',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
