# Generated by Django 2.2 on 2019-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0010_mpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpath',
            name='drive_memory_mb',
            field=models.IntegerField(default=8192),
        ),
    ]
