# Generated by Django 2.2 on 2019-10-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0011_mpath_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='src_mpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srcMpath', to='Mryang_App.MPath'),
        ),
        migrations.AlterField(
            model_name='media',
            name='desc_mpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='descMPath', to='Mryang_App.MPath'),
        ),
    ]
