# Generated by Django 2.2 on 2019-09-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0011_auto_20190912_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='picinfo',
            name='mpath',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mpath', to='Mryang_App.MPath'),
            preserve_default=False,
        ),
    ]
