# Generated by Django 2.2.5 on 2019-10-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0012_auto_20191003_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='folder_key',
        ),
    ]
