# Generated by Django 2.2 on 2019-09-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0012_picinfo_mpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picinfo',
            name='mpath',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mpath', to='Mryang_App.MPath'),
        ),
    ]
