# Generated by Django 2.2 on 2019-10-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0013_remove_media_folder_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='audio_long_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
