# Generated by Django 2.2 on 2019-09-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0014_auto_20190913_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpath',
            name='dir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Mryang_App.Dir'),
            preserve_default=False,
        ),
    ]
