# Generated by Django 2.2 on 2019-10-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0014_media_audio_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='audio_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
