# Generated by Django 2.2 on 2019-09-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0015_mpath_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpath',
            name='path',
        ),
        migrations.AlterField(
            model_name='mpath',
            name='dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mryang_App.Dir', unique=True),
        ),
    ]
