# Generated by Django 2.2 on 2019-09-14 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0017_auto_20190913_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpath',
            name='dir',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mryang_App.Dir'),
        ),
        migrations.AlterField(
            model_name='mpath',
            name='drive_memory_mb',
            field=models.IntegerField(default=8192, verbose_name='磁盘剩余空间小于此数值时,不选择此路径'),
        ),
        migrations.AlterField(
            model_name='mpath',
            name='level',
            field=models.IntegerField(default=0, verbose_name='放置优先级,数字越大优先级越高'),
        ),
        migrations.AlterField(
            model_name='mpath',
            name='type',
            field=models.IntegerField(default=0, verbose_name='文件夹的类型(1.src,2.desc)'),
        ),
    ]
