# Generated by Django 2.2 on 2019-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0018_auto_20190915_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryinfo',
            name='abs_path',
        ),
        migrations.RemoveField(
            model_name='galleryinfo',
            name='desc_path',
        ),
        migrations.RemoveField(
            model_name='galleryinfo',
            name='folder_key',
        ),
        migrations.CreateModel(
            name='TestMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_key', models.ManyToManyField(to='Mryang_App.MPath')),
            ],
        ),
    ]
