# Generated by Django 2.2 on 2019-09-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0019_auto_20190915_0728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMode',
        ),
    ]
