# Generated by Django 2.2 on 2019-09-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0020_delete_testmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_key', models.ManyToManyField(to='Mryang_App.MPath')),
            ],
        ),
    ]
