# Generated by Django 2.2 on 2019-09-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0021_testmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryinfo',
            name='mulit_path',
            field=models.ManyToManyField(to='Mryang_App.MPath'),
        ),
        migrations.DeleteModel(
            name='TestMode',
        ),
    ]
