# Generated by Django 2.2 on 2019-09-15 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0023_galleryinfo_src_real_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picinfo',
            name='mpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Mryang_App.MPath'),
        ),
    ]
