# Generated by Django 2.2 on 2019-09-15 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0024_auto_20190915_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picinfo',
            name='mpath',
        ),
        migrations.AddField(
            model_name='picinfo',
            name='desc_mpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='desc_mpath', to='Mryang_App.MPath'),
        ),
        migrations.AddField(
            model_name='picinfo',
            name='src_mpath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='src_mpath', to='Mryang_App.MPath'),
        ),
    ]
