# Generated by Django 2.2 on 2019-09-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0025_auto_20190915_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picinfo',
            name='src_mpath',
        ),
        migrations.AddField(
            model_name='picinfo',
            name='desc_root_dir',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='dir', to='Mryang_App.Dir'),
            preserve_default=False,
        ),
    ]
