# Generated by Django 2.2 on 2019-09-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0026_auto_20190915_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryinfo',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
