# Generated by Django 2.2 on 2019-09-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0027_galleryinfo_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picinfo',
            name='desc_root_dir',
        ),
        migrations.RemoveField(
            model_name='picinfo',
            name='src_abs_path',
        ),
        migrations.AddField(
            model_name='picinfo',
            name='src_dir',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='src_dir', to='Mryang_App.Dir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picinfo',
            name='src_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='galleryinfo',
            name='desc_real_path',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='picinfo',
            name='desc_name',
            field=models.CharField(max_length=100),
        ),
    ]
