# Generated by Django 2.2 on 2019-09-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0028_auto_20190915_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picinfo',
            name='src_dir',
        ),
        migrations.AddField(
            model_name='picinfo',
            name='src_mpath',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='src_mpath', to='Mryang_App.MPath'),
            preserve_default=False,
        ),
    ]
