# Generated by Django 2.2 on 2019-09-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mryang_App', '0029_auto_20190915_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='picinfo',
            name='src_abs_path',
            field=models.CharField(default='abc', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryinfo',
            name='src_real_path',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
